// Code generated by MockGen. DO NOT EDIT.
// Source: deleteUrl.go

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockURLDeleter is a mock of URLDeleter interface.
type MockURLDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockURLDeleterMockRecorder
}

// MockURLDeleterMockRecorder is the mock recorder for MockURLDeleter.
type MockURLDeleterMockRecorder struct {
	mock *MockURLDeleter
}

// NewMockURLDeleter creates a new mock instance.
func NewMockURLDeleter(ctrl *gomock.Controller) *MockURLDeleter {
	mock := &MockURLDeleter{ctrl: ctrl}
	mock.recorder = &MockURLDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLDeleter) EXPECT() *MockURLDeleterMockRecorder {
	return m.recorder
}

// DeleteURL mocks base method.
func (m *MockURLDeleter) DeleteURL(shortUrl string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteURL", shortUrl)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteURL indicates an expected call of DeleteURL.
func (mr *MockURLDeleterMockRecorder) DeleteURL(shortUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteURL", reflect.TypeOf((*MockURLDeleter)(nil).DeleteURL), shortUrl)
}
