// Code generated by MockGen. DO NOT EDIT.
// Source: redirect.go

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGetURL is a mock of GetURL interface.
type MockGetURL struct {
	ctrl     *gomock.Controller
	recorder *MockGetURLMockRecorder
}

// MockGetURLMockRecorder is the mock recorder for MockGetURL.
type MockGetURLMockRecorder struct {
	mock *MockGetURL
}

// NewMockGetURL creates a new mock instance.
func NewMockGetURL(ctrl *gomock.Controller) *MockGetURL {
	mock := &MockGetURL{ctrl: ctrl}
	mock.recorder = &MockGetURLMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetURL) EXPECT() *MockGetURLMockRecorder {
	return m.recorder
}

// GetURL mocks base method.
func (m *MockGetURL) GetURL(shortUrl string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURL", shortUrl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURL indicates an expected call of GetURL.
func (mr *MockGetURLMockRecorder) GetURL(shortUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURL", reflect.TypeOf((*MockGetURL)(nil).GetURL), shortUrl)
}
