name: Deploy App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  IMAGE_NAME: aixs/url-short
  SERVICE_NAME: app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build \
            --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -t $IMAGE_NAME:latest .

      - name: Run docker containers with Docker Compose
        run: docker-compose up -d

      - name: Run tests
        run: docker-compose run --rm $SERVICE_NAME go test ./...

      - name: Stop containers
        run: docker-compose down

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build \
            --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -t $IMAGE_NAME:latest .
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$(date +%Y%m%d%H%M%S)
          docker push $IMAGE_NAME:latest
