name: Build, Test and Push to Docker Hub

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  IMAGE_NAME: aixs/url-short
  SERVICE_NAME: app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:test .

      - name: Create env file
        run: |
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" > .env

      - name: Run docker containers with Docker Compose
        run: |
          docker-compose up -d

      - name: Run tests
        run: docker-compose run --rm $SERVICE_NAME go test ./...

      - name: Stop containers
        run: docker-compose down
        if: always()

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag and push Docker image
        run: |
          DATE_TAG=$(date +%Y%m%d%H%M%S)
          docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.IMAGE_NAME }}:$DATE_TAG
          docker push ${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.IMAGE_NAME }}:$DATE_TAG
